#!/bin/bash

connected=$(xrandr | grep 'HDMI-1 connected')

# подключен ли монитор
if [[ -z "$connected" ]]; then
    echo 'Монитор не подключен'

    # выключим отображение, если вдруг оно активно (просто был выдернут шнур)
    xrandr --output HDMI-1 --off
else
	# монитор подключен
	# проверим отображается ли он
	displayed=$(xrandr | grep 'HDMI-1 connected 2560x1440+2560+0')

	if [[ -z "$displayed" ]]; then
		# не отображается, включим отображение
		echo 'не отображается, включим отображение'
		xrandr --output eDP-1 --off
		xrandr --output HDMI-1 --mode 2560x1440 --pos 2560x0
		feh --bg-scale /home/sergey/Изображения/wallpaper.jpg
	else
		# отображается, выключим отображение
		echo 'отображается, выключим отображение'
		xrandr --output HDMI-1 --off
		xrandr --output eDP-1 --auto
	fi
fi
